# Change these first
owner: ali-hv # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Sky Backend
    url: https://sky.ezhoosh.com/api/v1/docs/
  - name: Sky Jitsi
    url: https://jitsi.ezhoosh.com
  - name: EzCRM
    url: https://api-users.ezhoosh.com/en/api/v1/docs/
  - name: EzRebar
    url: https://rebar-backend.ezhoosh.com/en/api/v1/docs/
  # - name: IPv6 test
  #   url: forwardemail.net
  #   port: 80
  #   check: "tcp-ping"
  #   ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/ali-hv/uptime/refs/heads/master/assets/upptime-icon.svg
  name: Uptime
  introTitle: "My services uptime monitoring"
  introMessage: This is a sample status page that uses github actions to monitor the uptime of my services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/ali-hv/uptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
